config/routes.rb
Nnmp::Application.routes.draw do
    root :to => "candidates#index"

    resources :users, :only => [ :show ]
    resources :sessions, :only => [ :new, :create, :destroy ]
    resources :candidates do
        resources :votes
    end
    resources :votes

    get "votes/get_to_edit"
    match "get-vote-to-edit" => "votes#get_to_edit"

    get "candidates/get_io"
    match "get-io" => "candidates#get_io"

    match "login" => "sessions#new"
    match "logout" => "sessions#destroy", :via => :delete

    namespace :dashboard do
        resources :users
        resources :areas
        resources :orgs
        resources :units
        resources :nominations
        resources :candidates

        get "nominations/get_to_edit"
        match "get-nomination-to-edit" => "nominations#get_to_edit"
        get "candidates/move_votes"
        match "move-votes" => "candidates#move_votes"
        get "candidates/get_to_edit"
        match "get-candidate-to-edit" => "candidates#get_to_edit"
        get "pages/get_comment"
        match "get-votes-comment" => "pages#get_comment"

        match "add-user" => "users#new", :as => "add_user"

        match "home-orgs" => "pages#home_orgs", :as => "home_orgs"

        match "/" => "pages#home", :as => "home"
        match "orgs-stat" => "pages#orgs_stat", :as => "orgs_stat"
    end
end

app/views/shared/_errors_block.html.erb
<div class="alert alert-error">
    <button type="button" class="closer close" data-dismiss="alert">×</button>
    <ul class="unstyled">
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= raw msg %></li>
        <% end %>
    </ul>
</div>

app/views/shared/_user_bar.html.erb
<div class="user-bar">
    <div class="pull-left">
        <h4><%= t("shared.common.title") %></h4>
    </div>
    <div class="pull-right">
        <ul class="unstyled inline">
            <li><span><%= t("shared.users.common.greeting") %></span><%= current_user.email %></li>
            <li><%= link_to t("shared.dashboard.common.come_in_link"), dashboard_home_path %></li>
            <li><%= link_to t("shared.users.logout"), logout_path, :method => "delete" %></li>
        </ul>
    </div>
</div>

app/views/shared/_user_bar_admin.html.erb
<div class="user-bar">
    <div class="pull-left">
        <h4><%= t("shared.dashboard.common.title_bar_html") %></h4>
    </div>
    <div class="pull-right">
        <ul class="unstyled inline">
            <li><span><%= t("shared.users.common.greeting") %></span><%= current_user.email %></li>
            <li><%= link_to t("shared.users.logout"), logout_path, :method => "delete" %></li>
        </ul>
    </div>
</div>