config/routes.rb
Nnmp::Application.routes.draw do
    root :to => "candidates#index"

    resources :users, :only => [ :show ]
    resources :sessions, :only => [ :new, :create, :destroy ]
    resources :candidates do
        resources :votes
    end
    resources :votes

    get "votes/get_to_edit"
    match "get-vote-to-edit" => "votes#get_to_edit"

    get "candidates/get_io"
    match "get-io" => "candidates#get_io"

    match "login" => "sessions#new"
    match "logout" => "sessions#destroy", :via => :delete

    namespace :dashboard do
        resources :users
        resources :areas
        resources :orgs
        resources :units
        resources :nominations
        resources :candidates

        get "nominations/get_to_edit"
        match "get-nomination-to-edit" => "nominations#get_to_edit"
        get "candidates/move_votes"
        match "move-votes" => "candidates#move_votes"
        get "candidates/get_to_edit"
        match "get-candidate-to-edit" => "candidates#get_to_edit"
        get "pages/get_comment"
        match "get-votes-comment" => "pages#get_comment"

        match "add-user" => "users#new", :as => "add_user"

        match "home-orgs" => "pages#home_orgs", :as => "home_orgs"

        match "/" => "pages#home", :as => "home"
        match "orgs-stat" => "pages#orgs_stat", :as => "orgs_stat"
    end
end

app/models/candidate.rb
class Candidate < ActiveRecord::Base
    attr_accessible :depart,
                    :fam_name,
                    :first_name,
                    :measures,
                    :nomination_id,
                    :org_id,
                    :sec_name,
                    :unit_id,
                    :ward 
    cattr_accessor :offset, :limit

    belongs_to :nomination
    belongs_to :org
    belongs_to :unit

    has_many :votes, :dependent => :destroy

    def paginate(page, per_page)
        self.offset = page
        self.limit = per_page
        self.find_by_sql "SELECT c.id, c.fam_name, c.first_name, c.sec_name, c.nomination_id, c.org_id
                          FROM candidates c
                          LIMIT #{per_page}
                          OFFSET #{(page - 1) * per_page}"
    end

    def self.get_current_year_voted()
        self.joins("LEFT OUTER JOIN votes ON candidates.id = votes.candidate_id").where("votes.updated_at >= '#{Time.now.beginning_of_year}'").uniq
    end

    def this_year_votes_count()
        votes.where("updated_at >= '#{Time.now.beginning_of_year}'").count
    end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
    before_filter :autorization_check
    caches_action :index, :layout => false

    helper_method :sort_column, :sort_direction

    #caches_page :index

    def index
        @title = I18n.t('shared.common.candidates.title')
        @candidates = Candidate.get_current_year_voted #Candidate.where("updated_at >= ?", Time.now.beginning_of_year)
        #                       .order(:fam_name, :first_name, :sec_name, :org_id)
        #                       .all()
        #if !params[:search].blank?
        #    @search_phrase = params[:search].scan(/\S+/)
        #    tmp = []
        #    @candidates.each do |c|
        #        @search_phrase.each do |s|
        #            if c.fam_name + c.first_name + c.sec_name =~ Regexp.new("(" + s + ")", true)
        #                tmp << c if @search_phrase.index(s) == @search_phrase.size - 1
        #            else
        #                break
        #            end
        #        end
        #    end
        #    @candidates = tmp
        #end
        @page = params[:page] || 1
        #@page = @page.to_i
        #per_page = 50
        #@pages = @candidates.size % per_page == 0 ? (1..( @candidates.size / per_page ).to_i).to_a : (1..(( @candidates.size / per_page ).to_i + 1)).to_a
        #@candidates = Candidate.find_by_sql "SELECT c.id, c.fam_name, c.first_name, c.sec_name, c.nomination_id, c.org_id
        #                  FROM candidates c
        #                  ORDER BY c.fam_name, c.first_name, c.sec_name, c.org_id"
        #@candidates = Candidate.paginate( @page, 3 )
    end

    def new
    end

    def create
    end

    def show
        session[:layout] = nil
        @candidate = Candidate.find(params[:id])
        @title = @candidate.fam_name + " " + @candidate.first_name + " " + @candidate.sec_name
        if current_user.admin?
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ?", "#{params[:id]}" ])
        else
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ? AND user_id = ?", "#{params[:id]}", current_user.id ])
        end
    end

    def get_io
        @names = Hash.new {}
        if params[:search_first]
            @names["names"] = Candidate.find_by_sql("SELECT c.first_name 
                                                     FROM candidates c
                                                     ORDER BY c.first_name").map { |c| c.first_name.to_s }.uniq.select { |c| c =~ Regexp.new( "^(" + params[:search_first] + ")", true ) }.collect { |c| { "name" => c } }
        elsif params[:search_sec]
            @names["names"] = Candidate.find_by_sql("SELECT c.sec_name 
                                                     FROM candidates c
                                                     ORDER BY c.sec_name").map { |c| c.sec_name.to_s }.uniq.select { |c| c =~ Regexp.new( "^(" + params[:search_sec] + ")", true ) }.collect { |c| { "name" => c } }
        end
        respond_to do |format|
           format.json { render :json => @names.to_json }
        end
    end

    private
        def sort_column
            if params[:sort] == "votes"
                "votes"
            else
                Candidate.column_names.include?(params[:sort]) ? params[:sort] : "fam_name"
            end
        end

        def sort_direction
            %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
        end
end

app/controllers/dashboard/candidates_controller.rb
class Dashboard::CandidatesController < ApplicationController
    before_filter :autorization_check
    caches_action :index, :layout => false

    layout "dashboard"

    def index
        @title = I18n.t("shared.common.candidates.title")
        @candidates = Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id")
        cookies.permanent[:visited] = "visit"
    end

    def show
        session[:layout] = true
        @candidate = Candidate.find(params[:id])
        @title = @candidate.fam_name + " " + @candidate.first_name + " " + @candidate.sec_name
        if current_user.admin?
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ?", "#{params[:id]}" ])
        else
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ? AND user_id = ?", "#{params[:id]}", current_user.id ])
        end
        render "/candidates/show"
    end

    def get_to_edit
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        val = params[:candidate_id]
        render :partial => "edit", :locals => { :candidate => Candidate.find(val) }
    end

    def update
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id]).update_attributes(params[:candidate])
        @candidates = Candidate.order("fam_name, first_name, sec_name, id").all
        respond_to do |format|
            format.js
        end
    end

    def move_votes
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @from_candidate = Candidate.find( params[:from] )
        @to_candidate = Candidate.find( params[:to] )
        @votes = Vote.find_all_by_candidate_id( @from_candidate.id )
        if !@votes.blank?
            @votes.each do |vote|
                vote.update_attributes( :candidate_id => @to_candidate.id )
            end
        end
        render :partial => "candidates", :locals => { :candidates => Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id") }
    end

    def destroy
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id])
        @candidate.destroy
        @val = params[:id]
    end
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/candidates/_vote.html.erb
<div class="text-right">
    <%= l vote.created_at, :format => :short_date %> | 
    <button class="edit-vote-front" value="<%= vote.id %>">Изменить</button> |&nbsp;&nbsp; 
    <%= link_to t("shared.dashboard.common.destroy_link_html"), [ vote ], :method => :delete %>
</div>
<blockquote>
    <% if !vote.voter_fio.blank? || !vote.voter_phone.blank? || !vote.comment.blank? %>
        <p><%= raw vote.comment.gsub(/(\r\n)/, '</p><p>') %></p>
        <% if !vote.voter_fio.blank? || !vote.voter_phone.blank? %>
            <small>
                <% if !vote.voter_fio.blank? %>
                    <strong><%= vote.voter_fio %></strong>
                    <% if !vote.voter_phone.blank? %>
                        , <%= vote.voter_phone %>
                    <% end %>
                <% else %>
                    <% if !vote.voter_phone.blank? %>
                        <%= t("shared.common.votes.voter_phone_only") %>: <%= vote.voter_phone %>
                    <% end %>
                <% end %>
            </small>
        <% end %>
    <% else %>
        <p class="notext"><%= t("shared.common.candidates.none_in_form") %></p>
    <% end %>
</blockquote>

app/views/candidates/create.html.erb
<h1>Candidates#create</h1>
<p>Find me in app/views/candidates/create.html.erb</p>

app/views/candidates/index.html.erb
<%# cache do %>
<div class="container-fluid">
    <div class="row-fluid">
        <h3><%= @title %></h3>
    </div>
    <div class="row-fluid">
        <div class="pull-left">
            <%= form_for candidates_path, :method => 'get', :html => { :class => "form-inline" } do %>
                <%= hidden_field_tag :direction, params[:direction] %>
                <%= hidden_field_tag :sort, params[:sort] %>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag t("shared.common.search"), :name => nil, :class => "btn-primary btn" %>
            <% end %>
        </div>
        <div class="pull-right">
            <%= link_to t("shared.common.votes.new.link"), new_vote_path, { :class => "btn" } %>
        </div>
    </div>
    <div class="row-fluid">
        <% if @candidates.blank? %>
            <p><%= t("shared.common.candidates.none") %></p>
        <% else %>
            <table class="table table-hover candidates">
                <thead>
                    <tr>
                        <th><%= sortable "fam_name", t("shared.common.candidates.fam_name") %></th>
                        <th><%= sortable "first_name", t("shared.common.candidates.first_name") %></th>
                        <th><%= sortable "sec_name", t("shared.common.candidates.sec_name") %></th>
                        <th><%= sortable "nomination_id", t("shared.common.candidates.nomination_id") %></th>
                        <th width="34%"><%= sortable "org_id", t("shared.common.candidates.org_id") %></th>
                        <th class="votes-count"><%= sortable "votes", t("shared.common.candidates.count") %></th>
                        <th class="vote-action"></th>
                    </tr>
                </thead>
                <tbody>
                    <% @candidates.each do |candidate| %>
                        <tr>
                            <td><%= link_to candidate.fam_name, candidate_path(candidate.id) %></td>
                            <td><%= link_to candidate.first_name, candidate_path(candidate.id) %></td>
                            <td><%= link_to candidate.sec_name, candidate_path(candidate.id) %></td>
                            <td><%= Nomination.find(candidate.nomination_id).name %></td>
                            <td><%= Org.find(candidate.org_id).name %></td>
                            <td class="votes-count"><%= candidate.votes.count %></td>
                            <td class="vote-action"><%= link_to t("shared.common.votes.new.link_html"), new_candidate_vote_path(candidate.id), { :class => "btn" } %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        <% end %>
    </div>
   <div class="pagination" align="center">
       <%#= paginate @candidates %>
   </div>
</div>
<%# end %>

app/views/candidates/new.html.erb
<h1>Candidates#new</h1>
<p>Find me in app/views/candidates/new.html.erb</p>

app/views/candidates/show.html.erb
<div class="container-fluid">
    <div class="row-fluid">
        <h3><%= @candidate.fam_name %> <%= @candidate.first_name %> <%= @candidate.sec_name %></h3>
    </div>
    <div class="row-fluid candidate-info">
        <ul class="unstyled">
            <li><strong><%= t("shared.common.candidates.nomination_id") %>:</strong> <%= Nomination.find(@candidate.nomination_id).name %></li>
            <li><strong><%= t("shared.common.candidates.org_id") %>:</strong> <%= Org.find(@candidate.org_id).name %></li>
            <% if !@candidate.unit_id.blank? %>
                <li><strong><%= t("shared.common.candidates.unit_id") %>:</strong> <%= Unit.find(@candidate.unit_id).name %></li>
            <% end %>
            <% if !@candidate.depart.blank? %>
                <li><strong><%= t("shared.common.candidates.depart") %>:</strong> <%= @candidate.depart %></li>
            <% end %>
            <% if !@candidate.ward.blank? %>
                <li><strong><%= t("shared.common.candidates.ward") %>:</strong> <%= @candidate.ward %></li>
            <% end %>
            <li><strong><%= t("shared.common.candidates.total_votes") %>:</strong> <%= @candidate.votes.count %></li>
        </ul>
    </div>
    <div class="row-fluid candidate-votes">
        <h4>
            <% if current_user.admin? %>
                <%= t("shared.common.candidates.all_forms") %>
            <% else %>
                <%= t("shared.common.candidates.your_forms") %>
            <% end %>
        </h4>
        <% if !@votes.blank? %>
            <% @votes.each do |vote| %>
                <div class="vote-container vote-<%= vote.id %>">
                    <%= render :partial => "/candidates/vote", :locals => { :vote => vote } %>
                </div>
            <% end %> 
        <% else %>
            <%= t("shared.common.candidates.noone_your_forms") %>
        <% end %>
    </div>
</div>