config/routes.rb
Nnmp::Application.routes.draw do
    root :to => "candidates#index"

    resources :users, :only => [ :show ]
    resources :sessions, :only => [ :new, :create, :destroy ]
    resources :candidates do
        resources :votes
    end
    resources :votes

    get "votes/get_to_edit"
    match "get-vote-to-edit" => "votes#get_to_edit"

    get "candidates/get_io"
    match "get-io" => "candidates#get_io"

    match "login" => "sessions#new"
    match "logout" => "sessions#destroy", :via => :delete

    namespace :dashboard do
        resources :users
        resources :areas
        resources :orgs
        resources :units
        resources :nominations
        resources :candidates

        get "nominations/get_to_edit"
        match "get-nomination-to-edit" => "nominations#get_to_edit"
        get "candidates/move_votes"
        match "move-votes" => "candidates#move_votes"
        get "candidates/get_to_edit"
        match "get-candidate-to-edit" => "candidates#get_to_edit"
        get "pages/get_comment"
        match "get-votes-comment" => "pages#get_comment"

        match "add-user" => "users#new", :as => "add_user"

        match "home-orgs" => "pages#home_orgs", :as => "home_orgs"

        match "/" => "pages#home", :as => "home"
        match "orgs-stat" => "pages#orgs_stat", :as => "orgs_stat"
    end
end

app/controllers/dashboard/areas_controller.rb
class Dashboard::AreasController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.areas.common.title")
        @areas = Area.all
        @area = Area.new
    end

    def create
        @area = Area.create!(params[:area])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/candidates_controller.rb
class Dashboard::CandidatesController < ApplicationController
    before_filter :autorization_check
    caches_action :index, :layout => false

    layout "dashboard"

    def index
        @title = I18n.t("shared.common.candidates.title")
        @candidates = Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id")
        cookies.permanent[:visited] = "visit"
    end

    def show
        session[:layout] = true
        @candidate = Candidate.find(params[:id])
        @title = @candidate.fam_name + " " + @candidate.first_name + " " + @candidate.sec_name
        if current_user.admin?
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ?", "#{params[:id]}" ])
        else
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ? AND user_id = ?", "#{params[:id]}", current_user.id ])
        end
        render "/candidates/show"
    end

    def get_to_edit
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        val = params[:candidate_id]
        render :partial => "edit", :locals => { :candidate => Candidate.find(val) }
    end

    def update
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id]).update_attributes(params[:candidate])
        @candidates = Candidate.order("fam_name, first_name, sec_name, id").all
        respond_to do |format|
            format.js
        end
    end

    def move_votes
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @from_candidate = Candidate.find( params[:from] )
        @to_candidate = Candidate.find( params[:to] )
        @votes = Vote.find_all_by_candidate_id( @from_candidate.id )
        if !@votes.blank?
            @votes.each do |vote|
                vote.update_attributes( :candidate_id => @to_candidate.id )
            end
        end
        render :partial => "candidates", :locals => { :candidates => Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id") }
    end

    def destroy
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id])
        @candidate.destroy
        @val = params[:id]
    end
end

app/controllers/dashboard/nominations_controller.rb
class Dashboard::NominationsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.nominations.common.title")
        @nominations = Nomination.order("name").all
        @nomination = Nomination.new
    end

    def create
        @nomination = Nomination.create!(params[:nomination])
        @nominations_n = Nomination.order("name").all
        respond_to do |format|
            format.js
            format.html
        end
    end

    def get_to_edit
        val = params[:nomination_id]
        render :partial => "edit_this_nomination", :locals => { :this_nomination => Nomination.find(val) }
    end

    def update
        @nomination = Nomination.find(params[:id]).update_attributes(params[:nomination])
        @nominations_n = Nomination.order("name").all
        respond_to do |format|
            format.js
        end
    end

    def destroy
        @nomination = Nomination.find(params[:id])
        begin
            @nomination.destroy
            @val = params[:id]
        rescue ActiveRecord::DeleteRestrictionError
            @nomination.errors.add( :base, I18n.t("errors.restrict_nom_cand") )
        end
    end
end

app/controllers/dashboard/orgs_controller.rb
class Dashboard::OrgsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.orgs.common.title")
        @areas = Area.order("id").all
        @org = Org.new
    end

    def create
        @org = Org.create!(params[:org])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < ApplicationController
    before_filter :autorization_check
    #caches_action :home, :layout => false

    layout "dashboard"

    def home
        #expire_action(:controller => '/dashboard/pages', :action => 'home')
        @nominations = Nomination.order("name").all
        if !params[:top].blank?
            @top_now = params[:top].to_i
            @top_text = I18n.t('shared.dashboard.common.top_all')
        else
            @top = 10
            @top_text = I18n.t('shared.dashboard.common.top_text') + @top.to_s
        end
        respond_to do |format|
            format.html
            format.xls { response.headers['Content-Disposition'] = "attachment; filename=\"#{t('shared.excel.book_names.nominations')}.xls\"" }
        end
    end

    def home_orgs
        @orgs = Org.order("id").all
    end

    def get_comment
        vote = Vote.find(params[:vote_id])
        if !vote.comment.blank?
            render :partial => "vote", :locals => { :vote => vote }
        else
            render :text => ""
        end
    end
end

app/controllers/dashboard/units_controller.rb
class Dashboard::UnitsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.units.common.title")
        @orgs = Org.order("id").all
        @unit = Unit.new
    end

    def create
        @unit = Unit.create!(params[:unit])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
    before_filter :admin_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.dashboard.users.title")
        @users = User.order("email asc").all
    end

    def new
        @title = I18n.t("shared.users.adding.title")
        @user = User.new
    end

    def create
        @user = User.new(params[:user])
        if @user.save
            redirect_to dashboard_users_path
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        User.find(params[:id]).destroy
        redirect_to dashboard_users_path
    end
end

app/helpers/dashboard/nominations_helper.rb
module Dashboard::NominationsHelper
end

app/views/dashboard/pages/_vote.html.erb
<div class="comment-baloon">
    <div class="arrow"></div>
    <div>
        <p><%= raw vote.comment.gsub(/(\r\n)/, '</p><p>') %></p>
        <% if !vote.voter_fio.blank? || !vote.voter_phone.blank? %>
            <p class="text-right">
                <span class="grey small">
                    <% if !vote.voter_fio.blank? %>
                        <strong><%= vote.voter_fio %></strong>
                        <% if !vote.voter_phone.blank? %>
                            , <%= vote.voter_phone %>
                        <% end %>
                    <% else %>
                        <% if !vote.voter_phone.blank? %>
                            <%= t("shared.common.votes.voter_phone_only") %>: <%= vote.voter_phone %>
                        <% end %>
                    <% end %>
                </span>
            </p>
        <% end %>
    </div>
</div>

app/views/dashboard/pages/home.html (copy).erb
<div id="main" class="span12">
    <ul class="unstyled nominations">
        <li class="nomination">
            <% @nominations.each do |nomination| %>
                <% if !nomination.candidates.blank? %>
                    <h4 class="n-name"><%= nomination.name %></h4>
                    <span class="grey small"><%= t('shared.dashboard.results.all') %><%= nomination.candidates.count %></span>
                    <ul class="unstyled candidates">
                        <% nomination.top_candidates(5).each do |candidate| %>
                            <li class="candidate">
                            <strong><%= link_to "#{candidate.fam_name} #{candidate.first_name} #{candidate.sec_name}", dashboard_candidate_path(candidate) %></strong>
                            <span class="label info"><%= t('shared.dashboard.results.all_votes') %><%= Vote.find_all_by_candidate_id(candidate.id).count %></span><br />
                                <div class="container-men">
                                    <% Vote.find_all_by_candidate_id(candidate.id).each do |vote| %>
                                        <%= content_tag(:div, :class=> ( 'active' if !vote.comment.blank? ), :id => "#{vote.id}") do %><% end %>
                                    <% end %>
                                </div>
                            </li>
                        <% end %>
                    </ul>
                    <span class="under"></span>
                <% end %>
            <% end %>
        </li>
    </ul>
</div>
<div id="comment"></div>

app/views/dashboard/pages/home.html.erb
<%= render "dashboard/shared/main_tabs" %>
<div id="main" class="span12 tab-panel">
    <div class="text-right actions">
        <%= link_to t('shared.dashboard.common.top', :text => @top_text), { :controller => "pages", :action => "home", :top => @top } %> | 
        <%= link_to t("shared.dashboard.common.excel_export"), { :controller => "pages", :action => "home", :format => :xls } %>
    </div>
    <ul class="unstyled nominations">
        <li class="nomination">
            <% @nominations.each do |nomination| %>
                <% if !nomination.candidates.blank? %>
                    <h4 class="n-name"><%= nomination.name %></h4>
                    <span class="grey small"><%= t('shared.dashboard.results.all') %><%= nomination.candidates.get_current_year_voted.count %></span>
                    <table width="90%">
                        <tbody>
                            <% nomination.top_candidates(@top_now).each do |candidate| %>
                                <tr>
                                    <td align="right" width="40%" style="padding-right: 5px;" ><%= link_to "#{candidate.fam_name} #{candidate.first_name} #{candidate.sec_name}", dashboard_candidate_path(candidate) %></td>
                                    <td width="40%">
                                        <div class="progress">
                                            <% if candidate.votes_count_this_year != 0 %>
                                                <div class="bar" style="width: 
                                                <%= candidate.votes_count_this_year.to_f/nomination.top_candidates(@top_now)[0].votes_count_this_year.to_f*100 %>%;"></div>
                                            <% else %>
                                                <div class="bar" style="width: 0%;"></div>
                                            <% end %>
                                        </div>
                                    </td>
                                    <td valign="middle" style="padding-left: 5px;"><%= candidate.votes_count_this_year %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                    <span class="under"></span>
                <% end %>
            <% end %>
        </li>
    </ul>
</div>
<div id="comment"></div>

app/views/dashboard/pages/home.xls.erb
<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook
    xmlns="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:o="urn:schemas-microsoft-com:office:office"
    xmlns:x="urn:schemas-microsoft-com:office:excel"
    xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
    xmlns:html="http://www.w3.org/TR/REC-html40">
    <Styles>
        <Style ss:ID="Default">
            <Alignment ss:Vertical="Top" ss:WrapText="1"/>
        </Style>
        <Style ss:ID="header">
            <Alignment ss:Horizontal="Center" ss:Vertical="Top" ss:WrapText="1"/>
            <Font ss:Bold="1" ss:Size="16"/>
        </Style>
        <Style ss:ID="t1">
            <Borders>
                <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
            </Borders>
        </Style>
        <Style ss:ID="t2">
            <Alignment ss:Horizontal="Center" ss:Vertical="Center"/>
            <Borders>
                <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
            </Borders>
        </Style>
        <Style ss:ID="th1">
            <Alignment ss:Horizontal="Center" ss:Vertical="Center" ss:WrapText="1"/>
            <Borders>
                <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1"/>
                <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1"/>
            </Borders>
            <Font ss:Bold="1"/>
        </Style>
    </Styles>
    <% @nominations.each do |nom| %>
        <Worksheet ss:Name="<%= nom.name[0..30] %>">
            <Table>
                <Column ss:AutoFitWidth="0" ss:Width="37.5" />
                <Column ss:AutoFitWidth="0" ss:Width="225" />
                <Column ss:AutoFitWidth="0" ss:Width="225" />
                <Column ss:AutoFitWidth="0" ss:Width="42" />
                <Column ss:AutoFitWidth="0" ss:Width="42.75" />
                <Column ss:AutoFitWidth="0" ss:Width="319.5" />
                <Column ss:AutoFitWidth="0" ss:Width="159" />
                <Column ss:AutoFitWidth="0" ss:Width="109.5" />

                <Row>
                    <Cell ss:StyleID="header" ss:MergeAcross="7"><Data ss:Type="String"><%= nom.name %></Data></Cell>
                </Row>
                <Row>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_01_html') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_02') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_03') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_04') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_05') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_06') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_07') %></Data></Cell>
                    <Cell ss:StyleID="th1"><Data ss:Type="String"><%= t('shared.excel.nominations.c_08') %></Data></Cell>
                </Row>
                <% nom.top_candidates(nom.candidates.count).each do |cand| %>
                    <Row>
                        <Cell ss:StyleID="t1" ss:MergeDown="<%= cand.votes.blank? ? 0 : cand.votes.count - 1 %>"><Data ss:Type="Number"><%= nom.top_candidates(nom.candidates.count).index(cand) + 1 %></Data></Cell>
                        <Cell ss:StyleID="t1" ss:MergeDown="<%= cand.votes.blank? ? 0 : cand.votes.count - 1 %>"><Data ss:Type="String"><%= cand.fam_name %> <%= cand.first_name %> <%= cand.sec_name %></Data></Cell>
                        <Cell ss:StyleID="t1" ss:MergeDown="<%= cand.votes.blank? ? 0 : cand.votes.count - 1 %>"><Data ss:Type="String"><%= Org.find(cand.org_id).name %></Data></Cell>
                        <Cell ss:StyleID="t1" ss:MergeDown="<%= cand.votes.blank? ? 0 : cand.votes.count - 1 %>"><Data ss:Type="Number"><%= cand.votes.count %></Data></Cell>
                        <% if !cand.votes.blank? %>
                            <Cell ss:StyleID="t1"><Data ss:Type="Number">1</Data></Cell>
                            <Cell ss:StyleID="t1"><Data ss:Type="String"><%= cand.votes[0].comment %></Data></Cell>
                            <Cell ss:StyleID="t1"><Data ss:Type="String"><%= cand.votes[0].voter_fio %></Data></Cell>
                            <Cell ss:StyleID="t1"><Data ss:Type="String"><%= cand.votes[0].voter_phone %></Data></Cell>
                        <% else %>
                            <Cell ss:StyleID="t2" ss:MergeAcross="3"><Data ss:Type="String"><%= t('shared.excel.nominations.no_one_vote') %></Data></Cell>                        
                        <% end %>
                    </Row>
                    <% if !cand.votes.blank? %>
                        <% cand.votes.each do |vote| %>
                            <% if vote.id != cand.votes[0].id %>
                                <Row>
                                    <Cell ss:Index="5" ss:StyleID="t1"><Data ss:Type="Number"><%= cand.votes.index(vote) + 1 %></Data></Cell>
                                    <Cell ss:Index="6" ss:StyleID="t1"><Data ss:Type="String"><%= vote.comment %></Data></Cell>
                                    <Cell ss:Index="7" ss:StyleID="t1"><Data ss:Type="String"><%= vote.voter_fio %></Data></Cell>
                                    <Cell ss:Index="8" ss:StyleID="t1"><Data ss:Type="String"><%= vote.voter_phone %></Data></Cell>
                                </Row>
                            <% end %>
                        <% end %>
                    <% end %>
                <% end %>
            </Table>
        </Worksheet>
    <% end %>
</Workbook>

app/views/dashboard/pages/home_orgs.html.erb
<%= render "dashboard/shared/main_tabs" %>
<div id="main" class="span12 tab-panel">
    <ul class="unstyled orgs">
        <% @orgs.each do |org| %>
            <% if !org.candidates.blank? %>
                <li class="org">
                    <h4 class="n-name"><%= org.name %></h4>
                    <span class="grey small"><%= t('shared.dashboard.results.all_org') %><%= org.candidates.get_current_year_voted.count %></span>
                    <table width="90%">
                        <tbody>
                            <% org.top_candidates(5).each do |candidate| %>
                                <tr>
                                    <td align="right" width="40%" style="padding-right: 5px;" ><%= link_to "#{candidate.fam_name} #{candidate.first_name} #{candidate.sec_name}", dashboard_candidate_path(candidate) %></td>
                                    <td width="40%">
                                        <div class="progress">
                                            <% if candidate.votes_count_this_year != 0 %>
                                                <div class="bar" style="width: 
                                                <%= candidate.votes_count_this_year.to_f/org.top_candidates(@top_now)[0].votes_count_this_year.to_f*100 %>%;"></div>
                                            <% else %>
                                                <div class="bar" style="width: 0%;"></div>
                                            <% end %>
                                        </div>
                                    </td>
                                    <td valign="middle" style="padding-left: 5px;"><%= candidate.votes_count_this_year %></td>
                                </tr>
                            <% end %>
                        </tbody>
                    </table>
                </li>
            <% end %>
        <% end %>
    </ul>
</div>

app/views/dashboard/pages/orgs_stat.html.erb
<h3>Info about candidates throught organizations</h3>