config/routes.rb
Nnmp::Application.routes.draw do
    root :to => "candidates#index"

    resources :users, :only => [ :show ]
    resources :sessions, :only => [ :new, :create, :destroy ]
    resources :candidates do
        resources :votes
    end
    resources :votes

    get "votes/get_to_edit"
    match "get-vote-to-edit" => "votes#get_to_edit"

    get "candidates/get_io"
    match "get-io" => "candidates#get_io"

    match "login" => "sessions#new"
    match "logout" => "sessions#destroy", :via => :delete

    namespace :dashboard do
        resources :users
        resources :areas
        resources :orgs
        resources :units
        resources :nominations
        resources :candidates

        get "nominations/get_to_edit"
        match "get-nomination-to-edit" => "nominations#get_to_edit"
        get "candidates/move_votes"
        match "move-votes" => "candidates#move_votes"
        get "candidates/get_to_edit"
        match "get-candidate-to-edit" => "candidates#get_to_edit"
        get "pages/get_comment"
        match "get-votes-comment" => "pages#get_comment"

        match "add-user" => "users#new", :as => "add_user"

        match "home-orgs" => "pages#home_orgs", :as => "home_orgs"

        match "/" => "pages#home", :as => "home"
        match "orgs-stat" => "pages#orgs_stat", :as => "orgs_stat"
    end
end

app/controllers/dashboard/areas_controller.rb
class Dashboard::AreasController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.areas.common.title")
        @areas = Area.all
        @area = Area.new
    end

    def create
        @area = Area.create!(params[:area])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/candidates_controller.rb
class Dashboard::CandidatesController < ApplicationController
    before_filter :autorization_check
    caches_action :index, :layout => false

    layout "dashboard"

    def index
        @title = I18n.t("shared.common.candidates.title")
        @candidates = Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id")
        cookies.permanent[:visited] = "visit"
    end

    def show
        session[:layout] = true
        @candidate = Candidate.find(params[:id])
        @title = @candidate.fam_name + " " + @candidate.first_name + " " + @candidate.sec_name
        if current_user.admin?
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ?", "#{params[:id]}" ])
        else
            @votes = Vote.find(:all, :order => "id", :conditions => [ "candidate_id = ? AND user_id = ?", "#{params[:id]}", current_user.id ])
        end
        render "/candidates/show"
    end

    def get_to_edit
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        val = params[:candidate_id]
        render :partial => "edit", :locals => { :candidate => Candidate.find(val) }
    end

    def update
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id]).update_attributes(params[:candidate])
        @candidates = Candidate.order("fam_name, first_name, sec_name, id").all
        respond_to do |format|
            format.js
        end
    end

    def move_votes
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @from_candidate = Candidate.find( params[:from] )
        @to_candidate = Candidate.find( params[:to] )
        @votes = Vote.find_all_by_candidate_id( @from_candidate.id )
        if !@votes.blank?
            @votes.each do |vote|
                vote.update_attributes( :candidate_id => @to_candidate.id )
            end
        end
        render :partial => "candidates", :locals => { :candidates => Candidate.get_current_year_voted.order("fam_name, first_name, sec_name, id") }
    end

    def destroy
        expire_action(:controller => '/dashboard/candidates', :action => 'index')
        @candidate = Candidate.find(params[:id])
        @candidate.destroy
        @val = params[:id]
    end
end

app/controllers/dashboard/nominations_controller.rb
class Dashboard::NominationsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.nominations.common.title")
        @nominations = Nomination.order("name").all
        @nomination = Nomination.new
    end

    def create
        @nomination = Nomination.create!(params[:nomination])
        @nominations_n = Nomination.order("name").all
        respond_to do |format|
            format.js
            format.html
        end
    end

    def get_to_edit
        val = params[:nomination_id]
        render :partial => "edit_this_nomination", :locals => { :this_nomination => Nomination.find(val) }
    end

    def update
        @nomination = Nomination.find(params[:id]).update_attributes(params[:nomination])
        @nominations_n = Nomination.order("name").all
        respond_to do |format|
            format.js
        end
    end

    def destroy
        @nomination = Nomination.find(params[:id])
        begin
            @nomination.destroy
            @val = params[:id]
        rescue ActiveRecord::DeleteRestrictionError
            @nomination.errors.add( :base, I18n.t("errors.restrict_nom_cand") )
        end
    end
end

app/controllers/dashboard/orgs_controller.rb
class Dashboard::OrgsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.orgs.common.title")
        @areas = Area.order("id").all
        @org = Org.new
    end

    def create
        @org = Org.create!(params[:org])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/pages_controller.rb
class Dashboard::PagesController < ApplicationController
    before_filter :autorization_check
    #caches_action :home, :layout => false

    layout "dashboard"

    def home
        #expire_action(:controller => '/dashboard/pages', :action => 'home')
        @nominations = Nomination.order("name").all
        if !params[:top].blank?
            @top_now = params[:top].to_i
            @top_text = I18n.t('shared.dashboard.common.top_all')
        else
            @top = 10
            @top_text = I18n.t('shared.dashboard.common.top_text') + @top.to_s
        end
        respond_to do |format|
            format.html
            format.xls { response.headers['Content-Disposition'] = "attachment; filename=\"#{t('shared.excel.book_names.nominations')}.xls\"" }
        end
    end

    def home_orgs
        @orgs = Org.order("id").all
    end

    def get_comment
        vote = Vote.find(params[:vote_id])
        if !vote.comment.blank?
            render :partial => "vote", :locals => { :vote => vote }
        else
            render :text => ""
        end
    end
end

app/controllers/dashboard/units_controller.rb
class Dashboard::UnitsController < ApplicationController
    before_filter :autorization_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.units.common.title")
        @orgs = Org.order("id").all
        @unit = Unit.new
    end

    def create
        @unit = Unit.create!(params[:unit])
        respond_to do |format|
            format.js
            format.html
        end
    end

    def destroy
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
    before_filter :admin_check

    layout "dashboard"

    def index
        @title = I18n.t("shared.dashboard.users.title")
        @users = User.order("email asc").all
    end

    def new
        @title = I18n.t("shared.users.adding.title")
        @user = User.new
    end

    def create
        @user = User.new(params[:user])
        if @user.save
            redirect_to dashboard_users_path
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def destroy
        User.find(params[:id]).destroy
        redirect_to dashboard_users_path
    end
end

app/helpers/dashboard/nominations_helper.rb
module Dashboard::NominationsHelper
end

app/views/dashboard/shared/_main_tabs.html.erb
<h4><%= t('shared.dashboard.common.results') %></h4>
<ul class="nav nav-tabs main-tabs">
    <%= content_tag :li, :class => ('active' if params[:action].eql?("home")) do %>
        <%= link_to t('shared.dashboard.menu.nominations_html'), dashboard_home_path %>
    <% end %>
    <%= content_tag :li, :class => ('active' if params[:action].include?("home_orgs")) do %>
        <%= link_to t('shared.orgs.common.title_html'), dashboard_home_orgs_path %>
    <% end %>
</ul>

app/views/dashboard/shared/_menu.html.erb
<ul class="nav nav-stacked dashboard-menu">
    <%= content_tag :li, :class => (params[:controller] == "dashboard/pages" ? 'home active' : 'home') do %>
        <%= link_to t('shared.dashboard.menu.home'), dashboard_home_path %>
    <% end %>
    <% if current_user.admin? %>
        <%= content_tag :li, :class => (params[:controller].include?("users") ? 'users active' : 'users') do %>
            <%= link_to t('shared.dashboard.menu.users'), dashboard_users_path %>
        <% end %>
    <% end %>
    <%= content_tag :li, :class => (params[:controller].include?("nominations") ? 'nominations active' : 'nominations') do %>
        <%= link_to t('shared.dashboard.menu.nominations'), dashboard_nominations_path %>
    <% end %>
    <%= content_tag :li, :class => (params[:controller].include?("orgs") || params[:controller].include?("units") || params[:controller].include?("areas") ? 'orgs active' : 'orgs') do %>
        <%= link_to t('shared.dashboard.menu.organizations'), dashboard_orgs_path %>
    <% end %>
    <%= content_tag :li, :class => (params[:controller].include?("candidates") ? 'candidates active' : 'candidates') do %>
        <%= link_to t('shared.dashboard.menu.candidates'), dashboard_candidates_path %>
    <% end %>
    <% if current_user.admin? %>
        <%= content_tag :li, :class => (params[:controller].include?("votes") ? 'votes active' : 'votes') do %>
            <%= link_to t('shared.dashboard.menu.filled_forms'), dashboard_home_path %>
        <% end %>
    <% end %>
</ul>

app/views/dashboard/shared/_org_tabs.html.erb
<h4><%= t("shared.orgs.common.main_title") %></h4>
<ul class="nav nav-tabs orgs-tabs">
    <%= content_tag :li, :class => ('active' if params[:controller].include?("areas")) do %>
        <%= link_to t('shared.areas.common.title_html'), dashboard_areas_path %>
    <% end %>
    <%= content_tag :li, :class => ('active' if params[:controller].include?("orgs")) do %>
        <%= link_to t('shared.orgs.common.title_html'), dashboard_orgs_path %>
    <% end %>
    <%= content_tag :li, :class => ('active' if params[:controller].include?("units")) do %>
        <%= link_to t('shared.units.common.title_html'), dashboard_units_path %>
    <% end %>
</ul>